fix: auth flow works, storing email and adress optionally
Huddle01/Google-Workspace-Add-On pull request #3
Opened 2024-08-08 07:00 UTC by ponikar

2024-08-29 13:48 UTC, arcinston commented
@ponikar one QOF improvement could be adding biome to this repo
you can use the config file biome.json from shinigami repo

there is a lot of var usage inherently in the code , when it was written 
now we can clean it up , add linting etc 

whats your opinion? @ponikar

2024-08-29 14:07 UTC, arcinston requested changes

2024-08-29 14:07 UTC, arcinston commented on src/utils.ts
> +      createdAt: string;
all we need for calenders is the name of the subdomain right?

rest info contains sensitive info like apikey projectid which should not be returned

@ponikar can discuss which fields are critical for the functioning of the calender func and future addons we might create on top of the apis

2024-08-29 14:07 UTC, arcinston commented on src/pages/addMeeting.ts
> +      updatedAt: "",
why store all this data (i.e url , createdAt , etc etc)

also the fetch subdomains query should not return this data if it is being used for calenders purposes

2024-08-29 14:07 UTC, arcinston commented on src/pages/addMeeting.ts
> +    address ? MyWalletAddress : MyEmailAddress
would prefer both MyWalletAddress and MyEmailAddress widget be rendered if both exist

2024-08-29 14:09 UTC, arcinston requested changes
another thing which can be added is onGmailCompose 

can figure it out together on what the best approach would be

2024-08-29 14:10 UTC, arcinston commented
also if i could try the test deployment on my work email : arush@huddle01.com 
would be great @ponikar

2024-08-30 06:04 UTC, ponikar commented on src/pages/addMeeting.ts
> +    address ? MyWalletAddress : MyEmailAddress
okay

2024-08-30 07:34 UTC, ponikar commented
@arcinston Yes, We can setup biome later, its not a priority now, once we make sure the calcom and gcal flow is working as expected.

2024-08-30 07:34 UTC, ponikar commented on appsscript.json
> +    "https://platform-api-darshan.huddle01.workers.dev/api/v2/calendar/subdomains",
Yes, we can update this once we assure its working fine.

2024-08-30 07:46 UTC, arcinston requested changes

2024-08-30 07:46 UTC, arcinston commented on src/pages/addMeeting.ts
> +    subdomainResponse.subdomains.push({
rm this , the api endpoint should return it by default

2024-08-30 07:50 UTC, arcinston commented
@ponikar i think biome should be added , we will find some minor mistakes 
we can add it seperately in a different PR later

2024-08-30 11:55 UTC, arcinston commented
found 2 bugs 
in case of app, it should be huddle01.app/room

<img width="645" alt="image" src="https://github.com/user-attachments/assets/7ccf10ae-9366-492a-9cba-c6189d216602">

second small issue
it says app.huddle01.com -> when it should be huddle01.app
in case of subdomain it should say subdomain.huddle01.app
 
<img width="294" alt="image" src="https://github.com/user-attachments/assets/5d10f463-d132-412a-81ba-69e23089b53c">

2024-09-03 10:36 UTC, arcinston requested changes

2024-09-26 06:02 UTC, merged